/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: {
          base: 'var(--bg-base)',
          surface: 'var(--bg-surface)',
          elevated: 'var(--bg-elevated)',
          overlay: 'var(--bg-overlay)',
          inverse: 'var(--bg-inverse)',
        },
        purple: {
          50: 'var(--purple-50)',
          100: 'var(--purple-100)',
          200: 'var(--purple-200)',
          500: 'var(--purple-500)',
          600: 'var(--purple-600)',
          700: 'var(--purple-700)',
          glow: 'var(--purple-glow)',
        },
        green: {
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          500: 'var(--green-500)',
          600: 'var(--green-600)',
          glow: 'var(--green-glow)',
        },
        blue: {
          100: 'var(--blue-100)',
          500: 'var(--blue-500)',
          glow: 'var(--blue-glow)',
        },
        amber: {
          100: 'var(--amber-100)',
          500: 'var(--amber-500)',
        },
        red: {
          100: 'var(--red-100)',
          500: 'var(--red-500)',
          glow: 'var(--red-glow)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          dim: 'var(--text-dim)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          default: 'var(--border-default)',
          strong: 'var(--border-strong)',
          brand: 'var(--border-brand)',
        },
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
        10: 'var(--space-10)',
        11: 'var(--space-11)',
        12: 'var(--space-12)',
        13: 'var(--space-13)',
        14: 'var(--space-14)',
        15: 'var(--space-15)',
        16: 'var(--space-16)',
        17: 'var(--space-17)',
        18: 'var(--space-18)',
        19: 'var(--space-19)',
        20: 'var(--space-20)',
        21: 'var(--space-21)',
        22: 'var(--space-22)',
        23: 'var(--space-23)',
        24: 'var(--space-24)',
      },
      borderRadius: {
        xs: 'var(--r-xs)',
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        '2xl': 'var(--r-2xl)',
        full: 'var(--r-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        'glow-purple': 'var(--glow-purple)',
        'glow-green': 'var(--glow-green)',
        'glow-red': 'var(--glow-red)',
        'glow-blue': 'var(--glow-blue)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        spring: 'var(--ease-spring)',
        smooth: 'var(--ease-smooth)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
        enter: 'var(--duration-enter)',
      },
      fontFamily: {
        heading: ["'Instrument Serif'", 'serif'],
        body: ["'Barlow'", 'sans-serif'],
        outfit: ["'Outfit'", 'sans-serif'],
        mono: ["'JetBrains Mono'", 'monospace'],
      },
    },
  },
  plugins: [],
}
