"""GitLab integration for Kira-AI coach alerts, audit logging, and monitoring.

Environment variables:
  - GITLAB_TOKEN: GitLab personal access token (required for integration)
  - GITLAB_PROJECT_ID: GitLab project numeric ID (required for integration)
  - GITLAB_API_URL: GitLab API base URL (default: https://gitlab.com/api/v4)

All functions gracefully degrade if integration is disabled (token/project not configured).
"""

from __future__ import annotations

import json
import logging
import os
from typing import Any, Optional
from urllib.parse import quote

import requests

LOGGER = logging.getLogger(__name__)

# Configuration from environment
GITLAB_TOKEN = os.getenv("GITLAB_TOKEN", "").strip()
GITLAB_PROJECT_ID = os.getenv("GITLAB_PROJECT_ID", "").strip()
GITLAB_API_URL = os.getenv("GITLAB_API_URL", "https://gitlab.com/api/v4").strip()
TIMEOUT_SECONDS = 8


def _is_enabled() -> bool:
    """Check if GitLab integration is enabled (both token and project ID configured)."""
    return bool(GITLAB_TOKEN and GITLAB_PROJECT_ID)


def _get_headers() -> dict[str, str]:
    """Return standard GitLab API headers."""
    return {
        "PRIVATE-TOKEN": GITLAB_TOKEN,
        "Content-Type": "application/json",
    }


def _build_issue_url() -> str:
    """Build the GitLab issues endpoint URL."""
    return f"{GITLAB_API_URL}/projects/{quote(GITLAB_PROJECT_ID, safe='')}/issues"


def _build_snippets_url() -> str:
    """Build the GitLab snippets endpoint URL."""
    return f"{GITLAB_API_URL}/projects/{quote(GITLAB_PROJECT_ID, safe='')}/snippets"


def create_coach_alert(session_id: str, coach_state: dict[str, Any]) -> Optional[str]:
    """
    Create a GitLab issue for critical coach alerts.

    Only creates an issue if:
    - GitLab integration is enabled
    - Coach status is "critical"

    Args:
        session_id: Unique session identifier
        coach_state: Coach workflow state dict containing signals and recommendations

    Returns:
        Issue web_url if successful, None on failure or if not critical
    """
    if not _is_enabled():
        return None

    status = coach_state.get("status", "")
    if status != "critical":
        return None

    try:
        # Extract signals from coach_state
        top_category = coach_state.get("top_category", "Unknown")
        narrative = coach_state.get("narrative", "")[:100]  # Max 100 chars
        action = coach_state.get("nudge", "")[:100]
        suggested_cap = coach_state.get("suggested_cap", 0)
        anomaly_score = coach_state.get("anomaly_score", 0.0)
        habit_score = coach_state.get("habit_score", 0.0)
        days_left = coach_state.get("days_left", "N/A")
        burn_rate = coach_state.get("burn_rate_daily", 0.0)
        confidence_score = coach_state.get("confidence_score", 0.0)

        # Build markdown table for description
        signals_table = f"""## Spending Coach Alert

| Signal | Value |
|--------|-------|
| Category | {top_category} |
| Anomaly Score | {anomaly_score:.2f} |
| Habit Score | {habit_score:.2f} |
| Days Left | {days_left} |
| Burn Rate (Daily) | ₹{burn_rate:.2f} |
| Suggested Cap | ₹{suggested_cap:.0f} |
| Confidence | {confidence_score:.2%} |

**Narrative**: {narrative}

**Recommended Action**: {action}

---
_Auto-generated by Kira-AI • Session: {session_id}_
"""

        payload = {
            "title": f"🚨 Kira Alert: {top_category} overspend | {session_id}",
            "description": signals_table,
            "labels": "kira-ai,coach-alert,critical,auto-generated",
            "confidential": True,
        }

        response = requests.post(
            _build_issue_url(),
            json=payload,
            headers=_get_headers(),
            timeout=TIMEOUT_SECONDS,
        )
        LOGGER.info(
            "GitLab create_coach_alert POST %s: status=%d, session_id=%s",
            _build_issue_url(),
            response.status_code,
            session_id,
        )

        if response.status_code in (200, 201):
            issue_data = response.json()
            web_url = issue_data.get("web_url")
            LOGGER.debug(f"Created GitLab issue: {web_url}")
            return web_url
        else:
            LOGGER.warning(
                "GitLab create_coach_alert failed: status=%d, response=%s",
                response.status_code,
                response.text[:200],
            )
            return None

    except Exception as exc:
        LOGGER.warning(f"GitLab create_coach_alert exception: {exc}", exc_info=True)
        return None


def close_resolved_alerts(session_id: str) -> None:
    """
    Close any open GitLab issues for a session that has returned to stable status.

    Searches for open issues matching the session_id and closes them with a comment.
    Gracefully handles failures without raising exceptions.

    Args:
        session_id: Unique session identifier
    """
    if not _is_enabled():
        return

    try:
        # Search for open issues with auto-generated label matching this session
        search_url = _build_issue_url()
        search_params = {
            "labels": "auto-generated",
            "state": "opened",
            "search": session_id,
        }

        response = requests.get(
            search_url,
            params=search_params,
            headers=_get_headers(),
            timeout=TIMEOUT_SECONDS,
        )
        LOGGER.info(
            "GitLab close_resolved_alerts GET %s: status=%d, session_id=%s",
            search_url,
            response.status_code,
            session_id,
        )

        if response.status_code != 200:
            LOGGER.warning(
                "GitLab close_resolved_alerts search failed: status=%d",
                response.status_code,
            )
            return

        issues = response.json()
        for issue in issues:
            iid = issue.get("iid")
            if not iid:
                continue

            # Close the issue
            close_url = f"{search_url}/{iid}"
            close_response = requests.put(
                close_url,
                json={"state_event": "close"},
                headers=_get_headers(),
                timeout=TIMEOUT_SECONDS,
            )
            LOGGER.info(
                "GitLab close_resolved_alerts PUT %s: status=%d",
                close_url,
                close_response.status_code,
            )

            if close_response.status_code not in (200, 201):
                LOGGER.warning(
                    "GitLab close_resolved_alerts close failed: status=%d, iid=%s",
                    close_response.status_code,
                    iid,
                )
                continue

            # Add closing comment
            notes_url = f"{close_url}/notes"
            comment_response = requests.post(
                notes_url,
                json={"body": "✅ Kira: Status returned to stable. Auto-resolved."},
                headers=_get_headers(),
                timeout=TIMEOUT_SECONDS,
            )
            LOGGER.info(
                "GitLab close_resolved_alerts POST comment %s: status=%d",
                notes_url,
                comment_response.status_code,
            )

    except Exception as exc:
        LOGGER.warning(f"GitLab close_resolved_alerts exception: {exc}", exc_info=True)


def log_coach_run(session_id: str, coach_state: dict[str, Any]) -> None:
    """
    Log a coach run as a private GitLab snippet for audit trail.

    Creates an immutable audit record of each coach workflow execution.
    Gracefully handles failures without raising exceptions.

    Args:
        session_id: Unique session identifier
        coach_state: Complete coach workflow state
    """
    if not _is_enabled():
        return

    try:
        timestamp = coach_state.get("timestamp", "unknown")
        payload = {
            "title": f"Coach Run: {session_id} ({timestamp})",
            "file_name": "coach_run.json",
            "content": json.dumps(coach_state, indent=2, default=str),
            "visibility": "private",
        }

        response = requests.post(
            _build_snippets_url(),
            json=payload,
            headers=_get_headers(),
            timeout=TIMEOUT_SECONDS,
        )
        LOGGER.info(
            "GitLab log_coach_run POST %s: status=%d, session_id=%s",
            _build_snippets_url(),
            response.status_code,
            session_id,
        )

        if response.status_code not in (200, 201):
            LOGGER.warning(
                "GitLab log_coach_run failed: status=%d, response=%s",
                response.status_code,
                response.text[:200],
            )

    except Exception as exc:
        LOGGER.warning(f"GitLab log_coach_run exception: {exc}", exc_info=True)


def get_open_alerts_count() -> int:
    """
    Get the count of open Kira-AI alerts in GitLab.

    Returns:
        Number of open issues with kira-ai label, or 0 on failure or if disabled
    """
    if not _is_enabled():
        return 0

    try:
        search_params = {
            "labels": "kira-ai",
            "state": "opened",
        }

        response = requests.get(
            _build_issue_url(),
            params=search_params,
            headers=_get_headers(),
            timeout=TIMEOUT_SECONDS,
        )
        LOGGER.info(
            "GitLab get_open_alerts_count GET %s: status=%d",
            _build_issue_url(),
            response.status_code,
        )

        if response.status_code != 200:
            LOGGER.warning(
                "GitLab get_open_alerts_count failed: status=%d",
                response.status_code,
            )
            return 0

        issues = response.json()
        count = len(issues)
        LOGGER.debug(f"GitLab open alerts count: {count}")
        return count

    except Exception as exc:
        LOGGER.warning(f"GitLab get_open_alerts_count exception: {exc}", exc_info=True)
        return 0